import { Bug, Plus } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import FailureTable from '../../components/qa/FailureTable'
import EvidencePanel from '../../components/qa/EvidencePanel'
import BugDraftDialog from '../../components/qa/BugDraftDialog'
import { Button } from '../../components/ui/button'
import type { FailuresIndexProps, FailureRow } from '../../types/props'

export default function FailuresIndex({ failures, modules }: FailuresIndexProps) { const [params, setParams] = useSearchParams(); const [selected, setSelected] = useState<string[]>([]); const [openFailure, setOpenFailure] = useState<FailureRow | null>(null); const [bugOpen, setBugOpen] = useState(false); const [toast, setToast] = useState(''); useEffect(() => { const id = params.get('open'); if (id) setOpenFailure(failures.find(failure => failure.id === id) ?? null) }, [params, failures]); const notify = (message: string) => { setToast(message); setBugOpen(false); window.setTimeout(() => setToast(''), 2800) }; return <><div className="page-heading"><div><h1>Failures</h1><div className="page-subtitle">Triage signatures from the latest runs.</div></div><div className="page-heading-actions"><Button variant="outline" disabled={!selected.length} onClick={() => setBugOpen(true)}><Bug size={13} />File bug{selected.length ? ` (${selected.length})` : ''}</Button><Button onClick={() => setParams({ category: 'needs_triage' })}><Plus size={14} />Add filter</Button></div></div><div className="toolbar"><select className="select" value={params.get('category') ?? 'all'} onChange={event => setParams({ category: event.target.value })}><option value="all">All categories</option><option value="product_bug">Product bug</option><option value="flaky">Flaky</option><option value="test_broken">Test broken</option><option value="environment">Environment</option><option value="needs_triage">Needs triage</option><option value="quarantined">Quarantined</option></select><select className="select"><option>All modules</option>{modules.map(module => <option key={module}>{module}</option>)}</select><span className="chip chip-triage">11 open signatures</span><span className="small muted">18 tests in 11 signatures</span><input className="input" placeholder="Search signature or test" /></div><FailureTable failures={failures} selected={selected} onSelectedChange={setSelected} onOpen={failure => { setOpenFailure(failure); setParams({ open: failure.id }) }} />{openFailure && <EvidencePanel failure={openFailure} open onClose={() => { setOpenFailure(null); setParams({}) }} onNotify={notify} />}{bugOpen && <BugDraftDialog failures={failures.filter(failure => selected.includes(failure.id))} onClose={() => setBugOpen(false)} onSave={notify} />}{toast && <div className="toast">{toast}</div>}</> }
