import { Check, ShieldCheck, X } from 'lucide-react'
import { useState } from 'react'
import type { Category } from '../../types/domain'
import type { FailureRow } from '../../types/props'
import { categoryKeys, categoryTokens } from '../../lib/tokens'
import { Button } from '../ui/button'
import { Sheet, SheetContent } from '../ui/sheet'

export default function EvidencePanel({ failure, open, onClose, onNotify }: { failure: FailureRow | null; open: boolean; onClose: () => void; onNotify: (message: string) => void }) { const [category, setCategory] = useState<Category>(failure?.category ?? 'needs_triage'); if (!failure) return null; return <Sheet open={open}><SheetContent className="evidence-sheet"><div className="modal-header"><div><div className="modal-title">Failure evidence</div><div className="modal-description">{failure.module} · {failure.group}</div></div><button className="icon-button" onClick={onClose}><X size={15} /></button></div><div className="sheet-body"><div><div className="table-primary">{failure.signature}</div><div className="mono" style={{ marginTop: 5 }}>{failure.filePath}</div></div><div className="evidence-image">Screenshot placeholder · evidence attached</div><EvidenceBlock label="Error message"><pre>{failure.errorMessage}</pre></EvidenceBlock><EvidenceBlock label="Last step reached"><div className="small" style={{ marginTop: 7 }}>{failure.lastStep}</div></EvidenceBlock><EvidenceBlock label="Stack trace"><pre>{failure.stack}</pre></EvidenceBlock><EvidenceBlock label="Log excerpt"><pre>{failure.logExcerpt}</pre></EvidenceBlock><EvidenceBlock label="Commit"><div className="mono" style={{ marginTop: 7 }}>{failure.commit}</div></EvidenceBlock><EvidenceBlock label="Change category"><select className="select select-wide" style={{ marginTop: 7 }} value={category} onChange={event => setCategory(event.target.value as Category)}>{categoryKeys.map(key => <option value={key} key={key}>{categoryTokens[key].label}</option>)}</select><div className="small muted" style={{ marginTop: 5 }}><Check size={12} style={{ verticalAlign: -2 }} /> Saved as a QA override</div></EvidenceBlock><div className="side-actions"><Button variant="outline" onClick={() => onNotify('Test quarantined')}><ShieldCheck size={13} />Quarantine</Button>{failure.bugLink ? <Button variant="outline" onClick={() => onNotify(`Comment added to ${failure.bugLink?.adoId}`)}>Comment on {failure.bugLink.adoId}</Button> : <Button onClick={() => onNotify('Bug draft created')}>File bug</Button>}</div></div></SheetContent></Sheet> }
function EvidenceBlock({ label, children }: { label: string; children: React.ReactNode }) { return <div className="evidence-block"><div className="label">{label}</div>{children}</div> }
